export const ActionType = {
    GET_RESOURCES_COUNT_PENDING:"GET_RESOURCES_COUNT_PENDING",
    GET_RESOURCES_COUNT_SUCCESS:"GET_RESOURCES_COUNT_SUCCESS",
    GET_RESOURCES_COUNT_FAILURE:"GET_RESOURCES_COUNT_FAILURE",
}